require("patches.aai-loader-electricity")
require("patches.arig-tweaks")
require("patches.hovercraft-integration")
require("patches.kry-inserters-lignumis-fix")
require("patches.muluna-tweaks")
require("patches.turbobike-integration")
