require("patches.aai-loader-electricity")
-- require("patches.battleship-integration")
require("patches.cargo-ships-revert-pelagos-changes")
require("patches.hoverbike-integration")
require("patches.hovercraft-integration")
require("patches.ironclad-nauvis")
require("patches.lignumis-kry-inserters-compat")
